version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customer-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bp0qmdxpxpp9"
s3_prefix = "customer-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
